export type Improvement = { id: string; title: string; status: "déjà intégré" | "à tester" | "à développer" | "inutile"; reason: string; source: string; priority: string };
const thread = "Three Morice upgrades worth testing now";
const entries: [string, Improvement["status"], string, string][] = [
  ["Mémoire commune et contexte de conversation", "déjà intégré", "Mémoire et historique sauvegardés; le contexte est envoyé au moteur. Test de restitution effectué dans Morice.", "P1"],
  ["Microsoft Outlook et agenda", "déjà intégré", "Lecture réelle Microsoft Graph. Agenda revérifié depuis la conversation le 18 septembre 2026. Une seule connexion; pas encore le classement de plusieurs boîtes.", "P1"],
  ["Recherche Web avec sources", "déjà intégré", "Recherche réelle vérifiée dans Morice le 18 septembre : outil Web, sources, résultat et historique retrouvés après rechargement. La présence de sources ne garantit pas l’exactitude de chaque affirmation.", "P1"],
  ["Lecteur vocal avec pause, vitesse et déplacement", "à tester", "Audio réel testé sur ordinateur le 18 septembre : lecture, pause, vitesses et déplacement. Réponses limitées à 4 000 caractères. Test humain sur Z Fold encore nécessaire; voix synthétique distincte de la dictée.", "P1"],
  ["Dictée manuelle et widget Android", "à tester", "Enregistrement manuel et APK signée disponibles. Installation et longue dictée humaine sur le téléphone à confirmer.", "P1"],
  ["File persistante et travaux de nuit", "à développer", "Historique et recherches distantes développés. La récupération reprend à l’ouverture de Morice. Planification autonome, rappels et notifications hors consultation restent à raccorder.", "P1"],
  ["MultipleChat : équipe interne de MORICE", "à développer", "Compte Smart actif vérifié le 18 septembre. Aucun accès API exposé dans Compte/Gestion. Session navigateur authentifiée disponible; pont automatique non établi.", "P1"],
  ["Recherche, vérification, débat et expertise multi-IA", "à tester", "Modes observés dans MultipleChat. Comparer résultat, coût et contradictions; ne pas solliciter quatre modèles pour une simple note.", "P1"],
  ["Avis neutres et critiques croisées", "à développer", "Alan demande une comparaison indépendante des fournisseurs et une synthèse des désaccords. Évaluer les propositions sur la fiabilité, le coût et les preuves.", "P1"],
  ["ChatGPT Work et navigateur authentifié", "à tester", "Piste de l’historique : utiliser les sessions connectées pour les actions web. Les connecteurs de cette tâche ne sont pas automatiquement ceux du serveur Morice.", "P1"],
  ["Work : déclencheurs d’apps et webhooks", "à tester", "Vérifier les déclencheurs réellement disponibles sur le compte et la possibilité de recevoir un travail Morice. Aucun webhook Work créé ici.", "P1"],
  ["Pont plugins ChatGPT / Codex / MCP", "à développer", "Construire une liaison authentifiée, avec permissions limitées, journal et retour de résultat; aucun partage de cookies ou de clés côté navigateur.", "P1"],
  ["Application desktop unifiée Chat, Work et Codex", "déjà intégré", "Codex est utilisé pour développer et vérifier le projet. Cela ne constitue pas une liaison automatique entre le backend Morice et les plugins.", "P2"],
  ["OpenClaw : passerelle Windows et Android", "à développer", "Gateway 2026.8.1 vérifié sain le 18 septembre. Liaison site → Gateway encore absente; ne pas exposer le port local publiquement.", "P1"],
  ["OpenClaw 2.0 / 2026.9.1 / 2026.9.4", "à tester", "Annonces du fil : installation, sessions longues, Android, mémoire et mises à jour. Versions et migration à vérifier dans les sources officielles avant modification de l’installation fonctionnelle.", "P2"],
  ["OpenClaw : Control UI et conversations en skills", "à tester", "Réutiliser si disponible pour administrer tâches, permissions et routines; éviter de reconstruire une console équivalente.", "P2"],
  ["OpenClaw : réutilisation des accès IA existants", "à tester", "Vérifier les méthodes de connexion effectivement prises en charge et leurs limites. Un abonnement ne garantit pas un accès API illimité.", "P2"],
  ["Make Maia : création et diagnostic de scénarios", "à tester", "Évaluer sur le scénario existant avant de construire une nouvelle automatisation; fonction annoncée dans le fil, non testée sur le compte.", "P2"],
  ["Make AI Agents : sous-agents et mémoire", "à tester", "Piste pour délégation par domaine, reprise et limitation du contexte; vérifier consommation et accès du forfait.", "P2"],
  ["Make MCP Toolboxes et outils MCP externes", "à tester", "Tester une boîte limitée à un outil de lecture; réutiliser les scénarios existants avec résultats structurés.", "P1"],
  ["Make : modules comme outils", "à tester", "Peut réduire les petits scénarios intermédiaires. Aucun outil activé uniquement sur la base de son annonce.", "P2"],
  ["Make : tarification des tokens et coûts", "à tester", "Mesurer les crédits réellement consommés par un cas quotidien avant de comparer à Graph/OpenClaw/Work.", "P2"],
  ["Make xAI et Claude Fable 5.1", "à tester", "Comparer sur une tâche bornée, si accès existant disponible; ne pas ajouter automatiquement de compte ou de dépenses.", "P2"],
  ["Microsoft Copilot Studio : processus longs", "à tester", "Vérifier licence et accès avant benchmark; conserver Graph qui fonctionne déjà.", "P2"],
  ["Microsoft Work IQ : contexte et MCP", "à tester", "Annonce du fil à vérifier. Droits administrateur, disponibilité et éventuelle consommation à établir; aucun remplacement automatique de Graph.", "P2"],
  ["Outlook Copilot : recherche et tri natifs", "à tester", "Tester disponibilité réelle, boîtes prises en charge et catégories avant de développer le même service.", "P1"],
  ["Classement de cinq ou six boîtes mail", "à développer", "Connecter chaque boîte autorisée, proposer les catégories puis appliquer un plan vérifiable. Ne pas confondre nombre de comptes et nombre de mails.", "P1"],
  ["Mail déplacé vers À traiter → To Do", "à développer", "Ne créer des tâches que pour les mails explicitement actionnables. Une notification ou un nouveau mail ne doit pas devenir automatiquement une tâche.", "P1"],
  ["HubSpot Agent Hub, Breeze et Agent Builder", "à tester", "Dépend des droits professionnels et du forfait. Conserver la pause du formulaire/HubSpot jusqu’au cadrage après la réunion.", "P3"],
  ["HubSpot clés de service et évolution des accès", "à tester", "Vérifier la transition annoncée dans la documentation et sur le compte. Ne pas créer de nouvelle clé ni élargir les permissions sans nécessité.", "P3"],
  ["HubSpot Data Studio webhooks et Agent CLI", "à tester", "Pistes du fil pour données et automatisations CRM; accès professionnel non établi.", "P3"],
  ["Galerie clients → pièces du formulaire Avisun", "à développer", "Conserver le parcours demandé : identifier dossier/client, sélectionner documents, vérifier champs et soumettre après validation. Projet formulaire actuellement en attente.", "P3"],
  ["One UI 9 : contexte, Now Nudge et confidentialité", "à tester", "Vérifier version, région et fonctions présentes sur le Z Fold. Une annonce de déploiement ne prouve pas leur présence sur cet appareil.", "P2"],
  ["Gemini Intelligence : actions Android multi-apps", "à tester", "Comparer avec Tasker et OpenClaw sur une action réversible; vérifier compatibilité des applications du téléphone.", "P1"],
  ["Gemini comme remplaçant de Google Assistant", "à tester", "Auditer les raccourcis existants avant migration. Conserver les commandes fiables et le widget Morice.", "P2"],
  ["Gemini Live / Gemini 3.8 Live", "à tester", "Benchmark vocal à prévoir : interruptions, outils pendant la conversation, mémoire et retour audio. Disponibilité réelle et coût non vérifiés.", "P2"],
  ["GPT-Live et voix duplex", "à tester", "Comparer au circuit enregistrement → transcription → outils → réponse audio avant d’en faire une dépendance.", "P2"],
  ["ChatGPT Voice avec Project Morice", "à tester", "Alternative à tester pour discuter avec les fichiers du projet. Ne constitue pas le contrôle du téléphone depuis Morice.", "P2"],
  ["Gemini vidéo et analyse intégrale des démonstrations", "à développer", "Analyser texte, son et images des médias fournis et conserver les exigences. La vidéo Bracket22 n’est disponible ici que par son compte rendu historique; ne pas prétendre l’avoir revue.", "P1"],
  ["OpenAI Agents API : sessions persistantes", "à tester", "Documentation officielle retrouvée. Faire un essai isolé de reprise et d’outils avant migration; conserver les données et intégrations Morice.", "P2"],
  ["GPT-6 Astra High, Ultra ciblé", "à tester", "Préférence d’Alan pour le travail Codex. Le réglage du modèle de la tâche n’est pas confirmé par cette application; le backend conserve son modèle configuré.", "P2"],
  ["Gemini Flash / Claude : moteurs spécialisés", "à tester", "Benchmarks bornés sur qualité, coût et récupération après erreur. Les noms, tarifs et disponibilités annoncés dans le fil doivent être revérifiés.", "P2"],
  ["Plugins et skills portables", "à développer", "Capacités modulaires, contrats d’entrée/sortie et permissions communes, sans recoder chaque intégration pour chaque moteur.", "P2"],
  ["ChatGPT Library : dossiers et partage", "à tester", "Examiner permissions et récupération des documents du projet sans multiplier les copies.", "P2"],
  ["Library : Box, Dropbox, SharePoint", "à tester", "Réutiliser les sources réellement connectées; disponibilité annoncée dans le fil à vérifier sur le compte.", "P2"],
  ["OneNote / Samsung Notes", "à tester", "Tester le connecteur de notes disponible et la synchronisation; préserver les notes existantes.", "P2"],
  ["Google Workspace Studio : flows et validations", "à tester", "Alternative secondaire si elle simplifie une action Android/Google; pas de migration d’office de l’architecture Microsoft.", "P3"],
  ["Grok Bot : agent persistant et intégration X", "à tester", "Demande explicite d’Alan : comparer sur 3 à 5 missions réelles, sans nouvel abonnement avant vérification des accès déjà payés.", "P2"],
  ["Grok / xAI : Web, X et outils", "à tester", "Moteur spécialisé distinct de Grok Bot. Vérifier l’accès disponible via MultipleChat et les éventuels coûts API séparés.", "P2"],
  ["Bracket22 : équipe de spécialistes et synthèse", "à développer", "Idée retenue de la vidéo : spécialistes technique, macro, informations et risques, puis synthèse argumentée. Sources et désaccords obligatoires; aucune décision financière autonome.", "P2"],
  ["Comptabilité personnelle, immo et B-MAC", "à développer", "Classer justificatifs par entité/comptable, détecter pièces manquantes et préparer les bilans. Envoi externe après examen du dossier.", "P2"],
  ["Comptes, Bankin/Revolut et patrimoine consolidé", "à développer", "Vue de lecture des comptes, immobilier, prêts et risques. Authentifications et droits nécessaires restent à établir.", "P2"],
  ["Crypto : Kraken, MetaMask, Phantom, Uniswap", "à développer", "Suivi de lecture, positions et alertes; intégrer DexScreener/CoinStats si accès adapté. Achats et signatures Ledger restent humains.", "P2"],
  ["Immobilier : dossiers et extranets", "à développer", "Dossiers par bien, loyers, travaux, assurances, prêts et échéances; accès aux extranets à vérifier individuellement.", "P2"],
  ["Maison, Dreame, four et Maurice le chien", "à développer", "Pièces, routines et suivi du chien Maurice. Le nom du chien est conservé; commandes domotiques à tester sur appareils réellement connectés.", "P3"],
  ["Impression 3D et nouvelles idées", "à développer", "Conserver les projets, fichiers, contraintes et recherches de matériel. Ne pas acheter ni lancer une machine sans instruction adaptée.", "P3"],
  ["Projet d’entreprise et recherches d’achat", "à développer", "Retenir objectifs et contraintes, rechercher les sources actuelles, produire options et prochaines actions dans Morice.", "P2"],
  ["Refonte sobre : logo et designs distincts", "à développer", "Conserver le logo exact. Concepts à faire valider après stabilisation fonctionnelle; aucune maquette choisie pour une nouvelle refonte.", "P3"],
  ["Application Morice de crédits de réinitialisation Codex", "inutile", "Les crédits concernent le compte Codex, pas une capacité du backend Morice. Les gérer dans Codex avec une autorisation par crédit.", "P3"],
  ["Repartir de zéro ou acheter tous les abonnements", "inutile", "L’existant fonctionne partiellement. Réutiliser les comptes et supprimer les doublons seulement après benchmark vérifié.", "P3"],
];
export const improvements: Improvement[] = entries.map(([title, status, reason, priority], i) => ({ id: `morice-upgrade-${i + 1}`, title, status, reason, source: thread, priority }));
