'use client';
import {useEffect,useState} from 'react';
type Meta={configured:boolean;name?:string;characters?:number;sha256?:string;updatedAt?:string};
export function CorePanel(){
 const [meta,setMeta]=useState<Meta>();const [file,setFile]=useState<File>();const [status,setStatus]=useState('');const [busy,setBusy]=useState(false);
 async function refresh(){const r=await fetch('/api/core');if(!r.ok)throw Error('Lecture CORE indisponible.');setMeta(await r.json() as Meta);}
 useEffect(()=>{const controller=new AbortController();void fetch('/api/core',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error('Lecture CORE indisponible.');return r.json();}).then(d=>{if(!controller.signal.aborted)setMeta(d as Meta);}).catch(()=>{if(!controller.signal.aborted)setStatus('Lecture CORE indisponible.');});return()=>controller.abort();},[]);
 async function upload(){if(!file||busy)return;setBusy(true);try{const body=new FormData();body.append('file',file);const r=await fetch('/api/core',{method:'POST',body});const result=await r.json() as {error?:string};if(!r.ok)throw Error(result.error||'Import non confirmé.');setFile(undefined);await refresh();setStatus('Référence importée et chiffrée. Les prochaines analyses utilisent des extraits pertinents du CORE.');}catch(e){setStatus(e instanceof Error?e.message:'Import interrompu.');}finally{setBusy(false);}}
 return <section className="panel"><p className="eyebrow">CONTEXTE PRIVÉ</p><h2>CORE Morice</h2><p>Le document consolidé reste privé et chiffré. GitHub et MultipleChat reçoivent uniquement CORE-SYNC, sans cet historique.</p>{meta?.configured?<><p>{meta.name} · {meta.characters?.toLocaleString('fr-FR')} caractères · importé le {new Date(meta.updatedAt!).toLocaleString('fr-FR')}</p><a href="/api/core?format=text" target="_blank" rel="noopener noreferrer">Consulter ma référence privée ↗</a></>:<p>Aucune référence privée importée dans ce runtime.</p>}<p>Une mise à jour conserve une copie chiffrée de la référence précédente.</p><label>Importer la référence TXT<input type="file" accept=".txt,text/plain" disabled={busy} onChange={e=>setFile(e.target.files?.[0])}/></label><button disabled={!file||busy} onClick={()=>void upload()}>{busy?'Import…':'Importer le CORE privé'}</button>{status&&<p role="status">{status}</p>}</section>;
}
