'use client';
import {useEffect,useRef,useState} from 'react';
import type {MailReview} from '../lib/mail-triage';

export function GoogleMailReviewPanel(){
 const [accounts,setAccounts]=useState<{id:string;email:string}[]>([]);const [id,setId]=useState('');const [review,setReview]=useState<MailReview|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [page,setPage]=useState(0);const request=useRef<AbortController|null>(null);
 useEffect(()=>{const c=new AbortController();fetch('/api/google/accounts',{signal:c.signal,cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json() as Promise<{accounts:{id:string;email:string}[]}>;}).then(d=>{if(!c.signal.aborted){setAccounts(d.accounts||[]);setId(d.accounts?.[0]?.id||'');}}).catch(()=>{if(!c.signal.aborted)setError('Liste Google indisponible.');});return()=>{c.abort();request.current?.abort();};},[]);
 async function load(){if(!id||busy)return;const c=new AbortController();request.current=c;setBusy(true);setError('');setReview(null);setPage(0);try{const r=await fetch(`/api/google/triage?accountId=${encodeURIComponent(id)}`,{cache:'no-store',signal:c.signal});const d=await r.json() as MailReview & {error?:string};if(!r.ok)throw Error(d.error||'Aperçu non confirmé.');if(!c.signal.aborted)setReview(d);}catch(e){if(!c.signal.aborted)setError(e instanceof Error?e.message:'Aperçu non confirmé.');}finally{if(request.current===c)setBusy(false);}}
 return <section className="panel" aria-label="Préparer le classement Gmail"><p className="eyebrow">GMAIL · LECTURE SEULE</p><h2>Préparer mon classement Gmail</h2><p>Jusqu’à 20 messages de la boîte de réception. Propositions par mots-clés dans l’objet et l’expéditeur ; ni contenu complet, ni pièces jointes analysés.</p>{accounts.length?<><label>Boîte Google <select value={id} disabled={busy} onChange={e=>{request.current?.abort();setId(e.target.value);setReview(null);setError('');setPage(0);}}>{accounts.map(a=><option key={a.id} value={a.id}>{a.email}</option>)}</select></label><button disabled={busy||!id} onClick={()=>void load()}>{busy?'Lecture Gmail en cours…':'Préparer l’aperçu Gmail'}</button></>:<p>Ajoutez votre boîte dans Connexions pour préparer son classement.</p>}{error&&<p role="alert">{error}</p>}{review&&<><p role="status">{review.account} · {review.messages.length} messages examinés · {new Date(review.checkedAt).toLocaleString('fr-FR')}. Aucun message modifié.</p><p>{review.hasMore?'D’autres messages restent à examiner. ':'Les autres dossiers ne sont pas inclus. '}Cet aperçu ne classe pas automatiquement la boîte et ne crée aucune tâche.</p><nav aria-label="Pages Gmail"><button disabled={page===0} onClick={()=>setPage(page-1)}>Précédente</button><span>Page {page+1} / {Math.max(1,Math.ceil(review.messages.length/10))}</span><button disabled={(page+1)*10>=review.messages.length} onClick={()=>setPage(page+1)}>Suivante</button></nav>{review.messages.slice(page*10,page*10+10).map(m=><article key={m.id} style={{padding:'1rem 0',borderTop:'1px solid var(--border)',overflowWrap:'anywhere'}}><h3>{m.subject}</h3><p>{m.sender} · {m.unread?'Non lu':'Lu'}</p><p><strong>{m.suggestions.join(' · ')||'À examiner'}</strong></p>{m.reasons.map(reason=><p key={reason}>{reason}</p>)}<p>{m.priority}</p></article>)}{!review.messages.length&&<p>Aucun message dans la boîte de réception.</p>}</>}</section>;
}
