plugins {
    id "com.android.application"
}

android {
    namespace "fr.alan.morice"
    compileSdk 36
    buildToolsVersion "36.0.0"

    defaultConfig {
        applicationId "fr.alan.morice"
        minSdk 26
        targetSdk 36
        versionCode 4
        versionName "1.1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation "androidx.browser:browser:1.9.0"
}
